const jsonexport = require("jsonexport");
const fs = require("fs");

const data = [
    {
        image:
            "https://ahprd1cdn.csgpimgs.com/i2/vcgU53TBVOIck3maYBi9DmRO8wF9nr-PcgXjUfYraX8/115/image.jpg",
        address: "750 W Hampden Ave Englewood, CO 80110",
        sf: "142,667",
        built: "1972",
        renovation: "1998",
        website: "http://omnidev.net/portfolio/hampden-center/",
        primaryLeasingCompany_Company: "Omni Development Corp",
        primaryLeasingCompany_Website: "http://www.omnidev.net/",
        primaryLeasingCompany_Name_1: "Dennis Witte",
        primaryLeasingCompany_Phone_1: "(303) 881-1350 (m)",
        primaryLeasingCompany_Email_1: "dwitte@omnidev.net",
        recordedOwner_Company: "Omni Development Corp",
        recordedOwner_Website: "http://www.omnidev.net/",
        propertyManagement_Company: "Omni Development Corp",
        propertyManagement_Website: "http://www.omnidev.net/",
        propertyManagement_Name_1: "Dallas Hidalgo",
        propertyManagement_Phone_1: "(303) 476-3081 (m)",
    },
    {
        image:
            "https://ahprd1cdn.csgpimgs.com/i2/cGvKHtKAZFSTAfTG3HEa-gPKYxmereIzVvFXgJn5A9U/119/image.jpg",
        address: "11960 Lioness Way - Lincoln Medical Center I Parker, CO 80134",
        sf: "115,362",
        built: "2008",
        website: "",
        primaryLeasingCompany_Company: "Healthcare Trust of America",
        primaryLeasingCompany_Website: "http://www.htareit.com/",
        primaryLeasingCompany_Name_1: "Bettina Hunt",
        primaryLeasingCompany_Phone_1: "(480) 436-4652 (m)",
        primaryLeasingCompany_Email_1: "bettinahunt@htareit.com",
        recordedOwner_Company: "Smmc Building 1 Llc",
        recordedOwner_Website: "http://www.htareit.com/",
        trueOwner_Company: "Healthcare Trust of America",
        trueOwner_Website: "http://www.htareit.com/",
        trueOwner_Name_1: "Robert Milligan",
        trueOwner_Phone_1: "(480) 998-3478 (p)",
        trueOwner_Email_1: "robertmilligan@htareit.com",
        propertyManagement_Company: "Healthcare Trust of America",
        propertyManagement_Website: "http://www.htareit.com/",
        previousTrueOwner_Company: "Healthcare Trust of America",
        previousTrueOwner_Website: "http://www.htareit.com/",
    },
    {
        image:
            "https://ahprd1cdn.csgpimgs.com/i2/zcDNfySM1VBzacmAHoVWOo38F77beGuxC7k8-tLxQZQ/119/image.jpg",
        address: "7901 E Lowry Blvd - The Quad at Lowry, Building 4 Denver, CO 80230",
        sf: "135,499",
        built: "2000",
        website: "",
        primaryLeasingCompany_Company: "Newmark",
        primaryLeasingCompany_Website: "http://www.ngkf.com/",
        primaryLeasingCompany_Name_1: "John Gustafson",
        primaryLeasingCompany_Phone_1: "(303) 917-8971 (m)",
        primaryLeasingCompany_Email_1: "jgustafson@ngkf.com",
        primaryLeasingCompany_Name_2: "Peter Staab",
        primaryLeasingCompany_Phone_2: "(303) 638-4020 (m)",
        primaryLeasingCompany_Email_2: "pstaab@ngkf.com",
        recordedOwner_Company: "Quad Partners LLC",
        recordedOwner_Website: "http://www.ngkf.com/",
        recordedOwner_Name_1: "Quad Partners LLC",
        trueOwner_Company: "HCA Management Company, LLC",
        trueOwner_Website: "http://www.ngkf.com/",
        previousTrueOwner_Company: "Schomac Group Inc",
        previousTrueOwner_Website: "http://www.ngkf.com/",
    },
    {
        image:
            "https://ahprd1cdn.csgpimgs.com/i2/wLV-c5o8e7Y9kxAhcyl34moFDrkoeL8ix3zYf3PJ7lY/119/image.jpg",
        address: "6200 S Syracuse Way - Carrara Place Englewood, CO 80111",
        sf: "237,681",
        built: "1982",
        renovation: "2017",
        website: "https://carraraplace.com/",
        primaryLeasingCompany_Company: "JLL",
        primaryLeasingCompany_Website: "http://www.jll.com/",
        primaryLeasingCompany_Name_1: "Andy Ross",
        primaryLeasingCompany_Phone_1: "(720) 308-4665 (m)",
        primaryLeasingCompany_Email_1: "Andy.Ross@am.jll.com",
        primaryLeasingCompany_Name_2: "John Beason",
        primaryLeasingCompany_Phone_2: "(720) 693-3781 (m)",
        primaryLeasingCompany_Email_2: "John.beason@am.jll.com",
        primaryLeasingCompany_Name_3: "Victoria Blackstock",
        primaryLeasingCompany_Phone_3: "(303) 981-2536 (m)",
        primaryLeasingCompany_Email_3: "Victoria.blackstock@am.jll.com",
        recordedOwner_Company: "New Carrara Llc",
        recordedOwner_Website: "http://www.jll.com/",
        trueOwner_Company: "DPC Development Companies",
        trueOwner_Website: "http://www.jll.com/",
        trueOwner_Name_1: "Justin Lutgen",
        trueOwner_Phone_1: "(720) 528-3349 X3349 (p)",
        trueOwner_Email_1: "jlutgen@dpccompanies.com",
        propertyManagement_Company: "DPC Development Companies",
        propertyManagement_Website: "http://www.jll.com/",
        propertyManagement_Name_1: "Jessica DiRe",
        propertyManagement_Phone_1: "(720) 528-3346 (p)",
        propertyManagement_Email_1: "jdire@dpccompanies.com",
        previousTrueOwner_Company: "PGIM, Inc.",
        previousTrueOwner_Website: "http://www.jll.com/",
        previousTrueOwner_Name_1: "Dean Deonaldo",
        previousTrueOwner_Phone_1: "(973) 803-8802 (m)",
        previousTrueOwner_Email_1: "dean.joseph.deonaldo@pgim.com",
    },
    {
        image:
            "https://ahprd1cdn.csgpimgs.com/i2/q9CWvpdbjKJqkzsfB3HqBl67GPc9ia5dkfS3VMmiufY/119/image.jpg",
        address: "6060 S Willow Dr - East Village Greenwood Village, CO 80111",
        sf: "138,125",
        built: "1982",
        renovation: "2020",
        website: "http://www.eastvillagedenver.com/",
        primaryLeasingCompany_Company: "CBRE",
        primaryLeasingCompany_Website: "http://www.cbre.us/",
        primaryLeasingCompany_Name_1: "John Marold",
        primaryLeasingCompany_Phone_1: "(720) 528-6355 (p)",
        primaryLeasingCompany_Email_1: "john.marold@cbre.com",
        primaryLeasingCompany_Name_2: "Sergio Castaneda",
        primaryLeasingCompany_Phone_2: "(303) 960-6314 (m)",
        primaryLeasingCompany_Email_2: "sergio.castaneda@cbre.com",
        primaryLeasingCompany_Name_3: "Mitch Bradley",
        primaryLeasingCompany_Phone_3: "(720) 528-6311 (p)",
        primaryLeasingCompany_Email_3: "mitch.bradley@cbre.com",
        recordedOwner_Company: "GC Net Lease (Greenwood Village) Investors, LLC",
        recordedOwner_Website: "http://www.cbre.us/",
        recordedOwner_Name_1: "GC Net Lease (Greenwood Village) Investors, LLC",
        trueOwner_Company: "Griffin Capital Essential Asset REIT, Inc.",
        trueOwner_Website: "http://www.cbre.us/",
        trueOwner_Name_1: "Julie Treinen",
        trueOwner_Phone_1: "(310) 469-6107 (p)",
        trueOwner_Email_1: "jtreinen@griffincapital.com",
        propertyManagement_Company: "Transwestern Real Estate Services",
        propertyManagement_Website: "http://www.cbre.us/",
        propertyManagement_Name_1: "Tina Richards",
        propertyManagement_Phone_1: "(303) 961-3778 (m)",
        propertyManagement_Email_1: "tina.richards@transwestern.com",
        previousTrueOwner_Company: "Travelers",
        previousTrueOwner_Website: "http://www.cbre.us/",
    },
    {
        image:
            "https://ahprd1cdn.csgpimgs.com/i2/jMw4EGUn-LFrFp3E_0uR5WFBLkVy8XTMO2S_dHU7hTg/119/image.jpg",
        address: "1560 Broadway - Civic Center Plaza Denver, CO 80202",
        sf: "598,592",
        built: "1983",
        website: "https://www.civiccenterdenver.com/",
        primaryLeasingCompany_Company: "JLL",
        primaryLeasingCompany_Website: "http://www.jll.com/",
        primaryLeasingCompany_Name_1: "Kevin Foley",
        primaryLeasingCompany_Phone_1: "(303) 542-1550 (p)",
        primaryLeasingCompany_Email_1: "kevin.p.foley@am.jll.com",
        primaryLeasingCompany_Name_2: "Andy Willson",
        primaryLeasingCompany_Phone_2: "(303) 947-8100 (m)",
        primaryLeasingCompany_Email_2: "Andy.willson@am.jll.com",
        recordedOwner_Company: "Civic Center Owner LLC",
        recordedOwner_Website: "http://www.jll.com/",
        trueOwner_Company: "Rising Realty Partners",
        trueOwner_Website: "http://www.jll.com/",
        trueOwner_Name_1: "Christopher Rising",
        trueOwner_Phone_1: "(213) 550-4859 (p)",
        trueOwner_Email_1: "christopher.rising@risingrp.com",
        propertyManagement_Company: "JLL",
        propertyManagement_Website: "http://www.jll.com/",
        propertyManagement_Name_1: "Kevin Foley",
        propertyManagement_Phone_1: "(303) 542-1550 (p)",
        propertyManagement_Email_1: "kevin.p.foley@am.jll.com",
        previousTrueOwner_Company: "Beacon Capital Partners",
        previousTrueOwner_Website: "http://www.jll.com/",
    },
    {
        image:
            "https://ahprd1cdn.csgpimgs.com/i2/9-jLDSNKtXr9eJwRbYYAe2QRq15uBuxrDgWru_Wpc-4/119/image.jpg",
        address: "400 S Colorado Blvd Denver, CO 80246",
        sf: "122,788",
        built: "1983",
        renovation: "2008",
        website: "https://dpccompanies.com/office-property/400-s-colorado?section=office",
        primaryLeasingCompany_Company: "CBRE",
        primaryLeasingCompany_Website: "http://www.cbre.us/",
        primaryLeasingCompany_Name_1: "Blake Holcomb",
        primaryLeasingCompany_Phone_1: "(303) 718-1389 (m)",
        primaryLeasingCompany_Email_1: "Blake.Holcomb@cbre.com",
        primaryLeasingCompany_Name_2: "Brian Hutt",
        primaryLeasingCompany_Phone_2: "(303) 349-3460 (m)",
        primaryLeasingCompany_Email_2: "brian.hutt@cbre.com",
        recordedOwner_Company: "BOF DPC 400 S Colorado LLC",
        recordedOwner_Website: "http://www.cbre.us/",
        trueOwner_Company: "Bridge Investment Group",
        trueOwner_Website: "http://www.cbre.us/",
        trueOwner_Name_1: "Christian Young",
        trueOwner_Phone_1: "(801) 580-3229 (m)",
        trueOwner_Email_1: "c.young@bridge-igh.com",
        propertyManagement_Company: "DPC Development Companies",
        propertyManagement_Website: "http://www.cbre.us/",
        previousTrueOwner_Company: "Bridge Commercial Real Estate",
        previousTrueOwner_Website: "http://www.cbre.us/",
    },
    {
        image:
            "https://ahprd1cdn.csgpimgs.com/i2/qVoEBWdXwbxg19Xc0jXoT-OHf0jG_0VGQ4C5S8LZM-g/119/image.jpg",
        address: "44 Cook St - First Avenue Plaza at Cherry Creek Denver, CO 80206",
        sf: "124,174",
        built: "1982",
        renovation: "2017",
        website:
            "https://www.cushmanwakefield.com/en/united-states/properties/for-lease/office/co/denver/44-cook-street-610/s40987s120325587-l",
        primaryLeasingCompany_Company: "Pinnacle Real Estate Advisors",
        primaryLeasingCompany_Website: "http://www.pinnaclerea.com/",
        primaryLeasingCompany_Name_1: "Jeff Caldwell",
        primaryLeasingCompany_Phone_1: "(303) 885-7633 (m)",
        primaryLeasingCompany_Email_1: "jcaldwell@pinnaclerea.com",
        recordedOwner_Company: "DPF Cherry Creek LLC",
        recordedOwner_Website: "http://www.pinnaclerea.com/",
        trueOwner_Company: "DPF CHERRY CREEK LLC",
        trueOwner_Website: "http://www.pinnaclerea.com/",
        propertyManagement_Company: "Cushman & Wakefield",
        propertyManagement_Website: "http://www.pinnaclerea.com/",
        propertyManagement_Name_1: "Sandy Grasso",
        propertyManagement_Phone_1: "(303) 889-8321 (p)",
        previousTrueOwner_Company: "Clarion Partners",
        previousTrueOwner_Website: "http://www.pinnaclerea.com/",
    },
    {
        image:
            "https://ahprd1cdn.csgpimgs.com/i2/lvjbcOgNgB2Lt6fP5PNn5aw3W-9pDkW1uj6l_3-6Iqc/119/image.jpg",
        address: "5619 DTC Pky - Terrace Tower Greenwood Village, CO 80111",
        sf: "254,283",
        built: "1984",
        renovation: "2000",
        website: "",
        primaryLeasingCompany_Company: "Transwestern Real Estate Services",
        primaryLeasingCompany_Website: "http://www.transwestern.com/",
        primaryLeasingCompany_Name_1: "Whitney Hake",
        primaryLeasingCompany_Phone_1: "(303) 601-6465 (m)",
        primaryLeasingCompany_Email_1: "Whitney.Hake@transwestern.com",
        primaryLeasingCompany_Name_2: "Billy Woodward",
        primaryLeasingCompany_Phone_2: "(303) 990-1625 (m)",
        primaryLeasingCompany_Email_2: "billy.woodward@transwestern.com",
        recordedOwner_Company: "Sun Life Assurance Company of Canada",
        recordedOwner_Website: "http://www.transwestern.com/",
        trueOwner_Company: "BentallGreenOak",
        trueOwner_Website: "http://www.transwestern.com/",
        trueOwner_Name_1: "Karin Benedetti",
        trueOwner_Phone_1: "1 (416) 371-5873 (m)",
        trueOwner_Email_1: "karin.benedetti@sunlife.com",
        propertyManagement_Company: "JLL",
        propertyManagement_Website: "http://www.transwestern.com/",
        propertyManagement_Name_1: "Paul Schloff",
        propertyManagement_Phone_1: "(303) 260-6525 (p)",
        propertyManagement_Email_1: "paul.schloff@am.jll.com",
        previousTrueOwner_Company: "Sun Life Assurance Company of Canada",
        previousTrueOwner_Website: "http://www.transwestern.com/",
    },
    {
        image:
            "https://ahprd1cdn.csgpimgs.com/i2/iL3vcJrJSxLa_pwzrCUlXPeztXvRFLNa_ciDe8dB3vM/119/image.jpg",
        address: "682 CTC Blvd - Building A Louisville, CO 80027",
        sf: "133,556",
        built: "2020",
        website: "",
        primaryLeasingCompany_Company: "Allen Company",
        primaryLeasingCompany_Website: "https://byallen.com/",
        primaryLeasingCompany_Name_1: "Brian Cavanaugh",
        primaryLeasingCompany_Phone_1: "(303) 981-1942 (m)",
        primaryLeasingCompany_Email_1: "brian.cavanaugh@allencompany.net",
        primaryLeasingCompany_Name_2: "George Cavanaugh",
        primaryLeasingCompany_Phone_2: "(720) 446-6334 (p)",
        primaryLeasingCompany_Email_2: "investmentsbybuckeye@gmail.com",
        recordedOwner_Company: "CTC PROPERTIES LLLP",
        recordedOwner_Website: "https://byallen.com/",
        recordedOwner_Name_1: "CTC PROPERTIES LLLP",
        trueOwner_Company: "Allen Company",
        trueOwner_Website: "https://byallen.com/",
        trueOwner_Name_1: "George Cavanaugh",
        trueOwner_Phone_1: "(970) 980-6375 (m)",
        trueOwner_Email_1: "consumerservice@allencompany.net",
    },
];

jsonexport(data, function (err, csv) {
    if (err) return console.error(err);
    console.log(csv);
    fs.writeFile("my.csv", csv, (err) => {
        if (err) throw err;
        console.log("my.csv saved.");
    });
});
